# Generated by Django 4.2.2 on 2024-04-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0004_bill_delivery_challan_reccurring_invoice_item_reccurring_invoice_reference_recurring_invoice_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_recieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(blank=True, max_length=220, null=True)),
                ('customer_billingaddress', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_GSTtype', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_GSTnumber', models.CharField(blank=True, max_length=220, null=True)),
                ('customer_place_of_supply', models.CharField(blank=True, max_length=220, null=True)),
                ('payment_date', models.DateField(null=True)),
                ('reference_number', models.IntegerField(blank=True, null=True)),
                ('payment_number', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=220, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=220, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=220, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_to_apply', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_to_credit', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.customer')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
