# Generated by Django 4.2.2 on 2024-04-16 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0017_alter_trialperiod_interested_in_buying'),
        ('Company_Staff', '0005_payment_recieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('invoice_amount', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=220, null=True)),
                ('invoice_type', models.CharField(blank=True, max_length=220, null=True)),
                ('Due_Date', models.DateField(null=True)),
                ('Date', models.DateField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
                ('payment_recieved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payment_recieved')),
            ],
        ),
    ]
