# Generated by Django 4.2.2 on 2024-05-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_payment_reference_payment_history_credit_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_recieved',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment_recieved',
            name='payment_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
